"use strict";
// 23. Conditional Tests: Write a series of conditional tests. Print a statement describing each test and 
// your prediction for the results of each test. Your code should look something like this:
let car = 'subaru';
console.log("Is car =='subaru'?|predict True.");
console.log(car === 'subaru');
// .look closly at your results, and make sure you understand why each line evaluates to True or False.
// . Create at least 10 tests. Have at least 5 tests evalute to True and another 5 tests evalutes to False.
console.log("Five tests for true results:");
console.log("Test 1:");
let num1 = 10;
console.log("If num1 === 10? than I predict ture.");
console.log(num1 === 10);
console.log("Test 2:");
let age = 45;
console.log("age === 45?  than  it's true.");
console.log(age === 45);
console.log("Test 3:");
const fname = "Shahab";
console.log("Check fname === 'shahab' than it is true.");
console.log(fname == "Shahab");
console.log("Test 4:");
let rollNo = "20ES15";
console.log("Check if Rollno == '20ES15' than predict ture");
console.log(rollNo == "20ES15");
console.log("Test 5:");
let caste = "Bhutto";
console.log("Is caste =='Bhutto' than  it is true");
console.log(caste == "Bhutto");
console.log("Five tests for false results:");
console.log("Test 6:");
let carName = "GLI";
console.log("carName == 'Caltus' than predict false. ");
console.log(carName == "Caltus");
console.log("Test 7");
let num = 27;
console.log("If num==26 than predict false.");
console.log(num == 26);
console.log("Test 8:");
var country = "Pakistan";
console.log("country =='india'  predict false.");
console.log(country == "india");
console.log("Test 9:");
var Province = "Sindh";
console.log("If Province == Punjab than it will be false");
console.log(Province == "Punjab");
console.log("Test 10:");
let Religion = "Islam";
console.log("If Religion =='Hinduisim' than it is false");
console.log(Religion == "Hinduism");
